### ISSUE TITLE
Create an iOS Build and deploy to App Store

### ISSUE THREAD

**Issue by vmohan7** [vmohan7/Navi#3]

**Comment by ddutchie** [comment]
I managed to build and deploy to my ios device. And connected to a macbook on a network. Good job.

**Comment by vmohan7** [comment]
Awesome! Glad to hear you were able to get it working. I tried to work on it last night and was able to get a build on my iPad; however, I got the error message:

"Error: Hack attack disconnect packet"

whenever the device attempted to connect to my PC. I was wondering if you ran into that issue and if you were able to solve that.

**Comment by ddutchie** [comment]
I tried on a ethernet pc with a wireless access point on the network (same domain and dhcp server) no go. Tried on my mac on the same wireless and it worked. The first time.

**Comment by vmohan7** [comment]
Yeah, just tried that now and it is exactly as you said, which is really weird. I am going to ask on the Unity forums to see if this is a bug.

**Comment by ddutchie** [comment]
Great. I'll comment and encourage activity there.

I'm very excited to try, but my vr pc only has ethernet and our office network consists of many hubs/switches/waps. 

But you are on the right track. Good job. I have done some experiments with the leap motion, perhaps their documents could provide some guidance on gestures. Eg: https://developer.leapmotion.com/documentation/csharp/devguide/Leap_Hand.html 

 I cant help you much on the coding side, but if you need 3d assets/promotional material. 

I'll be using this to navigate my VR architectural experiences. 

Regards
Gerard

**Comment by vmohan7** [comment]
Thanks! I just submitted to Unity answers, here is the link: 

http://answers.unity3d.com/questions/1041454/network-transport-layer-api-does-not-work-with-ios.html

I have not spent too much time looking at the Leap Motion but I think it would be really cool if it could be used to detect the tablet as well as your hands to provide more information to the system.

I would love help on all fronts especially 3d assets and promotional material. If you have any thoughts on how to spread the word / promote this, I am all ears. 

Thanks for all the help in trying to get this setup!
Vasanth

**Comment by ddutchie** [comment]
I meant to look at their documentation and how they have applied gestures to the three axis's, but thats interesting. 

They dont do object tracking yet. But the leap attaches really nicely to the dk2. And when it does, an smart watch/phone coup offer awesome interaction.

**Comment by vmohan7** [comment]
Finally got it to work with my PC. The problem was that I was using Unity 5.1.1 on my PC and 5.1.3 on my Mac. I have upgraded everything to 5.1.3 and now everything works!
